# -*- coding: utf-8 -*-

from . import res_partner
from . import account_chart_template
from . import res_company
from . import res_config_settings
from . import crm_lead
from . import broker_contract
from . import broker_contract_container
from . import broker_commission_insurer
from . import agreements_insurer
from . import coverage_template
from . import coverage_group
from . import broker_branch
from . import broker_claim_notice
from . import account_invoice
from . import sale_order
from . import sale_order_line
from . import sale_order_fee
from . import broker_object_deductible
from . import broker_movement_object
from . import broker_movement_stakeholder
from . import broker_presettlement
from . import broker_branch_insurer
from . import broker_business
from . import broker_movement_branch
from . import hr_employee
from . import mail_compose_message
from . import account_analytic_distribution_model
from . import broker_quota_cross
